/*================================================================================
  code generated by: java2cpp
  class: android.widget.DigitalClock
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_WIDGET_DIGITALCLOCK_HPP_DECL
#define J2CPP_ANDROID_WIDGET_DIGITALCLOCK_HPP_DECL


namespace j2cpp { namespace android { namespace content { class Context; } } }
namespace j2cpp { namespace android { namespace util { class AttributeSet; } } }


#include <android/content/Context.hpp>
#include <android/util/AttributeSet.hpp>


namespace j2cpp {

namespace android { namespace widget {

	class DigitalClock;
	class DigitalClock
		: public cpp_object<DigitalClock>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)

		DigitalClock(jobject jobj)
		: cpp_object<DigitalClock>(jobj)
		{
		}

	}; //class DigitalClock

} //namespace widget
} //namespace android


} //namespace j2cpp

#endif //J2CPP_ANDROID_WIDGET_DIGITALCLOCK_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_WIDGET_DIGITALCLOCK_HPP_IMPL
#define J2CPP_ANDROID_WIDGET_DIGITALCLOCK_HPP_IMPL

namespace j2cpp {


template <>
local_ref< android::widget::DigitalClock > create< android::widget::DigitalClock>(local_ref< android::content::Context > const &a0)
{
	return local_ref< android::widget::DigitalClock >(
		environment::get().get_jenv()->NewObject(
			get_class<android::widget::DigitalClock::J2CPP_CLASS_NAME>(),
			get_method_id<android::widget::DigitalClock::J2CPP_CLASS_NAME, android::widget::DigitalClock::J2CPP_METHOD_NAME(0), android::widget::DigitalClock::J2CPP_METHOD_SIGNATURE(0), false>(),
			a0.get_jtype()
		)
	);
}

template <>
local_ref< android::widget::DigitalClock > create< android::widget::DigitalClock>(local_ref< android::content::Context > const &a0, local_ref< android::util::AttributeSet > const &a1)
{
	return local_ref< android::widget::DigitalClock >(
		environment::get().get_jenv()->NewObject(
			get_class<android::widget::DigitalClock::J2CPP_CLASS_NAME>(),
			get_method_id<android::widget::DigitalClock::J2CPP_CLASS_NAME, android::widget::DigitalClock::J2CPP_METHOD_NAME(1), android::widget::DigitalClock::J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}




J2CPP_DEFINE_CLASS(android::widget::DigitalClock,"android/widget/DigitalClock")
J2CPP_DEFINE_METHOD(android::widget::DigitalClock,0,"<init>","(Landroid/content/Context;)V")
J2CPP_DEFINE_METHOD(android::widget::DigitalClock,1,"<init>","(Landroid/content/Context;Landroid/util/AttributeSet;)V")
J2CPP_DEFINE_METHOD(android::widget::DigitalClock,2,"onAttachedToWindow","()V")
J2CPP_DEFINE_METHOD(android::widget::DigitalClock,3,"onDetachedFromWindow","()V")

} //namespace j2cpp

#endif //J2CPP_ANDROID_WIDGET_DIGITALCLOCK_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
