/*================================================================================
  code generated by: java2cpp
  class: javax.crypto.Mac
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVAX_CRYPTO_MAC_HPP_DECL
#define J2CPP_JAVAX_CRYPTO_MAC_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }
namespace j2cpp { namespace java { namespace security { class Key; } } }
namespace j2cpp { namespace java { namespace security { class Provider; } } }
namespace j2cpp { namespace java { namespace security { namespace spec { class AlgorithmParameterSpec; } } } }
namespace j2cpp { namespace java { namespace nio { class ByteBuffer; } } }


#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <java/nio/ByteBuffer.hpp>
#include <java/security/Key.hpp>
#include <java/security/Provider.hpp>
#include <java/security/spec/AlgorithmParameterSpec.hpp>


namespace j2cpp {

namespace javax { namespace crypto {

	class Mac;
	class Mac
		: public cpp_object<Mac>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)
		J2CPP_DECLARE_METHOD(8)
		J2CPP_DECLARE_METHOD(9)
		J2CPP_DECLARE_METHOD(10)
		J2CPP_DECLARE_METHOD(11)
		J2CPP_DECLARE_METHOD(12)
		J2CPP_DECLARE_METHOD(13)
		J2CPP_DECLARE_METHOD(14)
		J2CPP_DECLARE_METHOD(15)
		J2CPP_DECLARE_METHOD(16)
		J2CPP_DECLARE_METHOD(17)

		Mac(jobject jobj)
		: cpp_object<Mac>(jobj)
		{
		}

		local_ref< java::lang::String > getAlgorithm();
		local_ref< java::security::Provider > getProvider();
		static local_ref< javax::crypto::Mac > getInstance(local_ref< java::lang::String > const&);
		static local_ref< javax::crypto::Mac > getInstance(local_ref< java::lang::String > const&, local_ref< java::lang::String > const&);
		static local_ref< javax::crypto::Mac > getInstance(local_ref< java::lang::String > const&, local_ref< java::security::Provider > const&);
		cpp_int getMacLength();
		void init(local_ref< java::security::Key > const&, local_ref< java::security::spec::AlgorithmParameterSpec > const&);
		void init(local_ref< java::security::Key > const&);
		void update(cpp_byte const&);
		void update(local_ref< cpp_byte_array<1> > const&, cpp_int const&, cpp_int const&);
		void update(local_ref< cpp_byte_array<1> > const&);
		void update(local_ref< java::nio::ByteBuffer > const&);
		local_ref< cpp_byte_array<1> > doFinal();
		void doFinal(local_ref< cpp_byte_array<1> > const&, cpp_int const&);
		local_ref< cpp_byte_array<1> > doFinal(local_ref< cpp_byte_array<1> > const&);
		void reset();
		local_ref< java::lang::Object > clone();
	}; //class Mac

} //namespace crypto
} //namespace javax


} //namespace j2cpp

#endif //J2CPP_JAVAX_CRYPTO_MAC_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVAX_CRYPTO_MAC_HPP_IMPL
#define J2CPP_JAVAX_CRYPTO_MAC_HPP_IMPL

namespace j2cpp {


template <>
local_ref< javax::crypto::Mac > create< javax::crypto::Mac>(local_ref< javax::crypto::MacSpi > const &a0, local_ref< java::security::Provider > const &a1, local_ref< java::lang::String > const &a2)
{
	return local_ref< javax::crypto::Mac >(
		environment::get().get_jenv()->NewObject(
			get_class<javax::crypto::Mac::J2CPP_CLASS_NAME>(),
			get_method_id<javax::crypto::Mac::J2CPP_CLASS_NAME, javax::crypto::Mac::J2CPP_METHOD_NAME(0), javax::crypto::Mac::J2CPP_METHOD_SIGNATURE(0), false>(),
			a0.get_jtype(), a1.get_jtype(), a2.get_jtype()
		)
	);
}

local_ref< java::lang::String > javax::crypto::Mac::getAlgorithm()
{
	return local_ref< java::lang::String >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(1), J2CPP_METHOD_SIGNATURE(1), false>()
		)
	);
}

local_ref< java::security::Provider > javax::crypto::Mac::getProvider()
{
	return local_ref< java::security::Provider >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(2), J2CPP_METHOD_SIGNATURE(2), false>()
		)
	);
}

local_ref< javax::crypto::Mac > javax::crypto::Mac::getInstance(local_ref< java::lang::String > const &a0)
{
	return local_ref< javax::crypto::Mac >(
		environment::get().get_jenv()->CallStaticObjectMethod(
			get_class<J2CPP_CLASS_NAME>(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(3), J2CPP_METHOD_SIGNATURE(3), true>(),
			a0.get_jtype()
		)
	);
}

local_ref< javax::crypto::Mac > javax::crypto::Mac::getInstance(local_ref< java::lang::String > const &a0, local_ref< java::lang::String > const &a1)
{
	return local_ref< javax::crypto::Mac >(
		environment::get().get_jenv()->CallStaticObjectMethod(
			get_class<J2CPP_CLASS_NAME>(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(4), J2CPP_METHOD_SIGNATURE(4), true>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

local_ref< javax::crypto::Mac > javax::crypto::Mac::getInstance(local_ref< java::lang::String > const &a0, local_ref< java::security::Provider > const &a1)
{
	return local_ref< javax::crypto::Mac >(
		environment::get().get_jenv()->CallStaticObjectMethod(
			get_class<J2CPP_CLASS_NAME>(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(5), J2CPP_METHOD_SIGNATURE(5), true>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

cpp_int javax::crypto::Mac::getMacLength()
{
	return cpp_int(
		environment::get().get_jenv()->CallIntMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(6), J2CPP_METHOD_SIGNATURE(6), false>()
		)
	);
}

void javax::crypto::Mac::init(local_ref< java::security::Key > const &a0, local_ref< java::security::spec::AlgorithmParameterSpec > const &a1)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(7), J2CPP_METHOD_SIGNATURE(7), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

void javax::crypto::Mac::init(local_ref< java::security::Key > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(8), J2CPP_METHOD_SIGNATURE(8), false>(),
			a0.get_jtype()
		)
	);
}

void javax::crypto::Mac::update(cpp_byte const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(9), J2CPP_METHOD_SIGNATURE(9), false>(),
			a0.get_jtype()
		)
	);
}

void javax::crypto::Mac::update(local_ref< cpp_byte_array<1> > const &a0, cpp_int const &a1, cpp_int const &a2)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(10), J2CPP_METHOD_SIGNATURE(10), false>(),
			a0.get_jtype(), a1.get_jtype(), a2.get_jtype()
		)
	);
}

void javax::crypto::Mac::update(local_ref< cpp_byte_array<1> > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(11), J2CPP_METHOD_SIGNATURE(11), false>(),
			a0.get_jtype()
		)
	);
}

void javax::crypto::Mac::update(local_ref< java::nio::ByteBuffer > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(12), J2CPP_METHOD_SIGNATURE(12), false>(),
			a0.get_jtype()
		)
	);
}

local_ref< cpp_byte_array<1> > javax::crypto::Mac::doFinal()
{
	return local_ref< cpp_byte_array<1> >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(13), J2CPP_METHOD_SIGNATURE(13), false>()
		)
	);
}

void javax::crypto::Mac::doFinal(local_ref< cpp_byte_array<1> > const &a0, cpp_int const &a1)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(14), J2CPP_METHOD_SIGNATURE(14), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

local_ref< cpp_byte_array<1> > javax::crypto::Mac::doFinal(local_ref< cpp_byte_array<1> > const &a0)
{
	return local_ref< cpp_byte_array<1> >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(15), J2CPP_METHOD_SIGNATURE(15), false>(),
			a0.get_jtype()
		)
	);
}

void javax::crypto::Mac::reset()
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(16), J2CPP_METHOD_SIGNATURE(16), false>()
		)
	);
}

local_ref< java::lang::Object > javax::crypto::Mac::clone()
{
	return local_ref< java::lang::Object >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(17), J2CPP_METHOD_SIGNATURE(17), false>()
		)
	);
}


J2CPP_DEFINE_CLASS(javax::crypto::Mac,"javax/crypto/Mac")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,0,"<init>","(Ljavax/crypto/MacSpi;Ljava/security/Provider;Ljava/lang/String;)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,1,"getAlgorithm","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,2,"getProvider","()Ljava/security/Provider;")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,3,"getInstance","(Ljava/lang/String;)Ljavax/crypto/Mac;")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,4,"getInstance","(Ljava/lang/String;Ljava/lang/String;)Ljavax/crypto/Mac;")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,5,"getInstance","(Ljava/lang/String;Ljava/security/Provider;)Ljavax/crypto/Mac;")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,6,"getMacLength","()I")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,7,"init","(Ljava/security/Key;Ljava/security/spec/AlgorithmParameterSpec;)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,8,"init","(Ljava/security/Key;)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,9,"update","(B)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,10,"update","([BII)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,11,"update","([B)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,12,"update","(Ljava/nio/ByteBuffer;)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,13,"doFinal","()[B")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,14,"doFinal","([BI)V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,15,"doFinal","([B)[B")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,16,"reset","()V")
J2CPP_DEFINE_METHOD(javax::crypto::Mac,17,"clone","()Ljava/lang/Object;")

} //namespace j2cpp

#endif //J2CPP_JAVAX_CRYPTO_MAC_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
