/*================================================================================
  code generated by: java2cpp
  class: java.io.FileReader
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_IO_FILEREADER_HPP_DECL
#define J2CPP_JAVA_IO_FILEREADER_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace io { class File; } } }
namespace j2cpp { namespace java { namespace io { class FileDescriptor; } } }


#include <java/io/File.hpp>
#include <java/io/FileDescriptor.hpp>
#include <java/lang/String.hpp>


namespace j2cpp {

namespace java { namespace io {

	class FileReader;
	class FileReader
		: public cpp_object<FileReader>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)

		FileReader(jobject jobj)
		: cpp_object<FileReader>(jobj)
		{
		}

	}; //class FileReader

} //namespace io
} //namespace java


} //namespace j2cpp

#endif //J2CPP_JAVA_IO_FILEREADER_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_IO_FILEREADER_HPP_IMPL
#define J2CPP_JAVA_IO_FILEREADER_HPP_IMPL

namespace j2cpp {


template <>
local_ref< java::io::FileReader > create< java::io::FileReader>(local_ref< java::io::File > const &a0)
{
	return local_ref< java::io::FileReader >(
		environment::get().get_jenv()->NewObject(
			get_class<java::io::FileReader::J2CPP_CLASS_NAME>(),
			get_method_id<java::io::FileReader::J2CPP_CLASS_NAME, java::io::FileReader::J2CPP_METHOD_NAME(0), java::io::FileReader::J2CPP_METHOD_SIGNATURE(0), false>(),
			a0.get_jtype()
		)
	);
}

template <>
local_ref< java::io::FileReader > create< java::io::FileReader>(local_ref< java::io::FileDescriptor > const &a0)
{
	return local_ref< java::io::FileReader >(
		environment::get().get_jenv()->NewObject(
			get_class<java::io::FileReader::J2CPP_CLASS_NAME>(),
			get_method_id<java::io::FileReader::J2CPP_CLASS_NAME, java::io::FileReader::J2CPP_METHOD_NAME(1), java::io::FileReader::J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype()
		)
	);
}

template <>
local_ref< java::io::FileReader > create< java::io::FileReader>(local_ref< java::lang::String > const &a0)
{
	return local_ref< java::io::FileReader >(
		environment::get().get_jenv()->NewObject(
			get_class<java::io::FileReader::J2CPP_CLASS_NAME>(),
			get_method_id<java::io::FileReader::J2CPP_CLASS_NAME, java::io::FileReader::J2CPP_METHOD_NAME(2), java::io::FileReader::J2CPP_METHOD_SIGNATURE(2), false>(),
			a0.get_jtype()
		)
	);
}


J2CPP_DEFINE_CLASS(java::io::FileReader,"java/io/FileReader")
J2CPP_DEFINE_METHOD(java::io::FileReader,0,"<init>","(Ljava/io/File;)V")
J2CPP_DEFINE_METHOD(java::io::FileReader,1,"<init>","(Ljava/io/FileDescriptor;)V")
J2CPP_DEFINE_METHOD(java::io::FileReader,2,"<init>","(Ljava/lang/String;)V")

} //namespace j2cpp

#endif //J2CPP_JAVA_IO_FILEREADER_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
