/*================================================================================
  code generated by: java2cpp
  author: Zoran Angelov, mailto://baldzar@gmail.com
  class: android.view.MotionEvent
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_VIEW_MOTIONEVENT_HPP_DECL
#define J2CPP_ANDROID_VIEW_MOTIONEVENT_HPP_DECL


namespace j2cpp { namespace android { namespace os { class Parcel; } } }
namespace j2cpp { namespace android { namespace os { class Parcelable; } } }
namespace j2cpp { namespace android { namespace os { namespace Parcelable_ { class Creator; } } } }
namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Object; } } }


#include <android/os/Parcel.hpp>
#include <android/os/Parcelable.hpp>
#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>


namespace j2cpp {

namespace android { namespace view {

	class MotionEvent;
	class MotionEvent
		: public object<MotionEvent>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)
		J2CPP_DECLARE_METHOD(8)
		J2CPP_DECLARE_METHOD(9)
		J2CPP_DECLARE_METHOD(10)
		J2CPP_DECLARE_METHOD(11)
		J2CPP_DECLARE_METHOD(12)
		J2CPP_DECLARE_METHOD(13)
		J2CPP_DECLARE_METHOD(14)
		J2CPP_DECLARE_METHOD(15)
		J2CPP_DECLARE_METHOD(16)
		J2CPP_DECLARE_METHOD(17)
		J2CPP_DECLARE_METHOD(18)
		J2CPP_DECLARE_METHOD(19)
		J2CPP_DECLARE_METHOD(20)
		J2CPP_DECLARE_METHOD(21)
		J2CPP_DECLARE_METHOD(22)
		J2CPP_DECLARE_METHOD(23)
		J2CPP_DECLARE_METHOD(24)
		J2CPP_DECLARE_METHOD(25)
		J2CPP_DECLARE_METHOD(26)
		J2CPP_DECLARE_METHOD(27)
		J2CPP_DECLARE_METHOD(28)
		J2CPP_DECLARE_METHOD(29)
		J2CPP_DECLARE_METHOD(30)
		J2CPP_DECLARE_METHOD(31)
		J2CPP_DECLARE_METHOD(32)
		J2CPP_DECLARE_METHOD(33)
		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)
		J2CPP_DECLARE_FIELD(2)
		J2CPP_DECLARE_FIELD(3)
		J2CPP_DECLARE_FIELD(4)
		J2CPP_DECLARE_FIELD(5)
		J2CPP_DECLARE_FIELD(6)
		J2CPP_DECLARE_FIELD(7)
		J2CPP_DECLARE_FIELD(8)
		J2CPP_DECLARE_FIELD(9)

		explicit MotionEvent(jobject jobj)
		: object<MotionEvent>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;
		operator local_ref<android::os::Parcelable>() const;


		static local_ref< android::view::MotionEvent > obtain(jlong, jlong, jint, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jint, jint);
		static local_ref< android::view::MotionEvent > obtain(jlong, jlong, jint, jfloat, jfloat, jint);
		static local_ref< android::view::MotionEvent > obtain(local_ref< android::view::MotionEvent >  const&);
		void recycle();
		jint getAction();
		jlong getDownTime();
		jlong getEventTime();
		jfloat getX();
		jfloat getY();
		jfloat getPressure();
		jfloat getSize();
		jint getMetaState();
		jfloat getRawX();
		jfloat getRawY();
		jfloat getXPrecision();
		jfloat getYPrecision();
		jint getHistorySize();
		jlong getHistoricalEventTime(jint);
		jfloat getHistoricalX(jint);
		jfloat getHistoricalY(jint);
		jfloat getHistoricalPressure(jint);
		jfloat getHistoricalSize(jint);
		jint getDeviceId();
		jint getEdgeFlags();
		void setEdgeFlags(jint);
		void setAction(jint);
		void offsetLocation(jfloat, jfloat);
		void setLocation(jfloat, jfloat);
		void addBatch(jlong, jfloat, jfloat, jfloat, jfloat, jint);
		local_ref< java::lang::String > toString();
		jint describeContents();
		void writeToParcel(local_ref< android::os::Parcel >  const&, jint);

		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(0), J2CPP_FIELD_SIGNATURE(0), jint > ACTION_DOWN;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(1), J2CPP_FIELD_SIGNATURE(1), jint > ACTION_UP;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(2), J2CPP_FIELD_SIGNATURE(2), jint > ACTION_MOVE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(3), J2CPP_FIELD_SIGNATURE(3), jint > ACTION_CANCEL;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(4), J2CPP_FIELD_SIGNATURE(4), jint > ACTION_OUTSIDE;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(5), J2CPP_FIELD_SIGNATURE(5), jint > EDGE_TOP;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(6), J2CPP_FIELD_SIGNATURE(6), jint > EDGE_BOTTOM;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(7), J2CPP_FIELD_SIGNATURE(7), jint > EDGE_LEFT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(8), J2CPP_FIELD_SIGNATURE(8), jint > EDGE_RIGHT;
		static static_field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(9), J2CPP_FIELD_SIGNATURE(9), local_ref< android::os::Parcelable_::Creator > > CREATOR;
	}; //class MotionEvent

} //namespace view
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_VIEW_MOTIONEVENT_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_VIEW_MOTIONEVENT_HPP_IMPL
#define J2CPP_ANDROID_VIEW_MOTIONEVENT_HPP_IMPL

namespace j2cpp {



android::view::MotionEvent::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jobject());
}

android::view::MotionEvent::operator local_ref<android::os::Parcelable>() const
{
	return local_ref<android::os::Parcelable>(get_jobject());
}


local_ref< android::view::MotionEvent > android::view::MotionEvent::obtain(jlong a0, jlong a1, jint a2, jfloat a3, jfloat a4, jfloat a5, jfloat a6, jint a7, jfloat a8, jfloat a9, jint a10, jint a11)
{
	return call_static_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(1),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(1), 
		local_ref< android::view::MotionEvent > >
	(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11);
}

local_ref< android::view::MotionEvent > android::view::MotionEvent::obtain(jlong a0, jlong a1, jint a2, jfloat a3, jfloat a4, jint a5)
{
	return call_static_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(2),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(2), 
		local_ref< android::view::MotionEvent > >
	(a0, a1, a2, a3, a4, a5);
}

local_ref< android::view::MotionEvent > android::view::MotionEvent::obtain(local_ref< android::view::MotionEvent > const &a0)
{
	return call_static_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(3),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(3), 
		local_ref< android::view::MotionEvent > >
	(a0);
}

void android::view::MotionEvent::recycle()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(4),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(4), 
		void >
	(get_jobject());
}

jint android::view::MotionEvent::getAction()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(5),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(5), 
		jint >
	(get_jobject());
}

jlong android::view::MotionEvent::getDownTime()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(6),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(6), 
		jlong >
	(get_jobject());
}

jlong android::view::MotionEvent::getEventTime()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(7),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(7), 
		jlong >
	(get_jobject());
}

jfloat android::view::MotionEvent::getX()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(8),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(8), 
		jfloat >
	(get_jobject());
}

jfloat android::view::MotionEvent::getY()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(9),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(9), 
		jfloat >
	(get_jobject());
}

jfloat android::view::MotionEvent::getPressure()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(10),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(10), 
		jfloat >
	(get_jobject());
}

jfloat android::view::MotionEvent::getSize()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(11),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(11), 
		jfloat >
	(get_jobject());
}

jint android::view::MotionEvent::getMetaState()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(12),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(12), 
		jint >
	(get_jobject());
}

jfloat android::view::MotionEvent::getRawX()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(13),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(13), 
		jfloat >
	(get_jobject());
}

jfloat android::view::MotionEvent::getRawY()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(14),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(14), 
		jfloat >
	(get_jobject());
}

jfloat android::view::MotionEvent::getXPrecision()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(15),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(15), 
		jfloat >
	(get_jobject());
}

jfloat android::view::MotionEvent::getYPrecision()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(16),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(16), 
		jfloat >
	(get_jobject());
}

jint android::view::MotionEvent::getHistorySize()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(17),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(17), 
		jint >
	(get_jobject());
}

jlong android::view::MotionEvent::getHistoricalEventTime(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(18),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(18), 
		jlong >
	(get_jobject(), a0);
}

jfloat android::view::MotionEvent::getHistoricalX(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(19),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(19), 
		jfloat >
	(get_jobject(), a0);
}

jfloat android::view::MotionEvent::getHistoricalY(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(20),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(20), 
		jfloat >
	(get_jobject(), a0);
}

jfloat android::view::MotionEvent::getHistoricalPressure(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(21),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(21), 
		jfloat >
	(get_jobject(), a0);
}

jfloat android::view::MotionEvent::getHistoricalSize(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(22),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(22), 
		jfloat >
	(get_jobject(), a0);
}

jint android::view::MotionEvent::getDeviceId()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(23),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(23), 
		jint >
	(get_jobject());
}

jint android::view::MotionEvent::getEdgeFlags()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(24),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(24), 
		jint >
	(get_jobject());
}

void android::view::MotionEvent::setEdgeFlags(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(25),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(25), 
		void >
	(get_jobject(), a0);
}

void android::view::MotionEvent::setAction(jint a0)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(26),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(26), 
		void >
	(get_jobject(), a0);
}

void android::view::MotionEvent::offsetLocation(jfloat a0, jfloat a1)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(27),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(27), 
		void >
	(get_jobject(), a0, a1);
}

void android::view::MotionEvent::setLocation(jfloat a0, jfloat a1)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(28),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(28), 
		void >
	(get_jobject(), a0, a1);
}

void android::view::MotionEvent::addBatch(jlong a0, jfloat a1, jfloat a2, jfloat a3, jfloat a4, jint a5)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(29),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(29), 
		void >
	(get_jobject(), a0, a1, a2, a3, a4, a5);
}

local_ref< java::lang::String > android::view::MotionEvent::toString()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(30),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(30), 
		local_ref< java::lang::String > >
	(get_jobject());
}

jint android::view::MotionEvent::describeContents()
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(31),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(31), 
		jint >
	(get_jobject());
}

void android::view::MotionEvent::writeToParcel(local_ref< android::os::Parcel > const &a0, jint a1)
{
	return call_method<
		android::view::MotionEvent::J2CPP_CLASS_NAME,
		android::view::MotionEvent::J2CPP_METHOD_NAME(32),
		android::view::MotionEvent::J2CPP_METHOD_SIGNATURE(32), 
		void >
	(get_jobject(), a0, a1);
}



static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(0),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(0),
	jint
> android::view::MotionEvent::ACTION_DOWN;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(1),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(1),
	jint
> android::view::MotionEvent::ACTION_UP;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(2),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(2),
	jint
> android::view::MotionEvent::ACTION_MOVE;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(3),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(3),
	jint
> android::view::MotionEvent::ACTION_CANCEL;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(4),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(4),
	jint
> android::view::MotionEvent::ACTION_OUTSIDE;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(5),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(5),
	jint
> android::view::MotionEvent::EDGE_TOP;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(6),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(6),
	jint
> android::view::MotionEvent::EDGE_BOTTOM;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(7),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(7),
	jint
> android::view::MotionEvent::EDGE_LEFT;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(8),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(8),
	jint
> android::view::MotionEvent::EDGE_RIGHT;

static_field<
	android::view::MotionEvent::J2CPP_CLASS_NAME,
	android::view::MotionEvent::J2CPP_FIELD_NAME(9),
	android::view::MotionEvent::J2CPP_FIELD_SIGNATURE(9),
	local_ref< android::os::Parcelable_::Creator >
> android::view::MotionEvent::CREATOR;


J2CPP_DEFINE_CLASS(android::view::MotionEvent,"android/view/MotionEvent")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,0,"<init>","()V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,1,"obtain","(JJIFFFFIFFII)Landroid/view/MotionEvent;")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,2,"obtain","(JJIFFI)Landroid/view/MotionEvent;")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,3,"obtain","(Landroid/view/MotionEvent;)Landroid/view/MotionEvent;")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,4,"recycle","()V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,5,"getAction","()I")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,6,"getDownTime","()J")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,7,"getEventTime","()J")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,8,"getX","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,9,"getY","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,10,"getPressure","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,11,"getSize","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,12,"getMetaState","()I")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,13,"getRawX","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,14,"getRawY","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,15,"getXPrecision","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,16,"getYPrecision","()F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,17,"getHistorySize","()I")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,18,"getHistoricalEventTime","(I)J")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,19,"getHistoricalX","(I)F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,20,"getHistoricalY","(I)F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,21,"getHistoricalPressure","(I)F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,22,"getHistoricalSize","(I)F")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,23,"getDeviceId","()I")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,24,"getEdgeFlags","()I")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,25,"setEdgeFlags","(I)V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,26,"setAction","(I)V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,27,"offsetLocation","(FF)V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,28,"setLocation","(FF)V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,29,"addBatch","(JFFFFI)V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,30,"toString","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,31,"describeContents","()I")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,32,"writeToParcel","(Landroid/os/Parcel;I)V")
J2CPP_DEFINE_METHOD(android::view::MotionEvent,33,"<clinit>","()V")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,0,"ACTION_DOWN","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,1,"ACTION_UP","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,2,"ACTION_MOVE","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,3,"ACTION_CANCEL","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,4,"ACTION_OUTSIDE","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,5,"EDGE_TOP","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,6,"EDGE_BOTTOM","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,7,"EDGE_LEFT","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,8,"EDGE_RIGHT","I")
J2CPP_DEFINE_FIELD(android::view::MotionEvent,9,"CREATOR","Landroid/os/Parcelable$Creator;")

} //namespace j2cpp

#endif //J2CPP_ANDROID_VIEW_MOTIONEVENT_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
