/*================================================================================
  code generated by: java2cpp
  class: junit.framework.TestResult
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JUNIT_FRAMEWORK_TESTRESULT_HPP_DECL
#define J2CPP_JUNIT_FRAMEWORK_TESTRESULT_HPP_DECL


namespace j2cpp { namespace junit { namespace framework { class TestListener; } } }
namespace j2cpp { namespace junit { namespace framework { class Test; } } }
namespace j2cpp { namespace junit { namespace framework { class AssertionFailedError; } } }
namespace j2cpp { namespace junit { namespace framework { class Protectable; } } }
namespace j2cpp { namespace java { namespace lang { class Throwable; } } }
namespace j2cpp { namespace java { namespace util { class Enumeration; } } }


#include <java/lang/Throwable.hpp>
#include <java/util/Enumeration.hpp>
#include <junit/framework/AssertionFailedError.hpp>
#include <junit/framework/Protectable.hpp>
#include <junit/framework/Test.hpp>
#include <junit/framework/TestListener.hpp>


namespace j2cpp {

namespace junit { namespace framework {

	class TestResult;
	class TestResult
		: public cpp_object<TestResult>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)
		J2CPP_DECLARE_METHOD(8)
		J2CPP_DECLARE_METHOD(9)
		J2CPP_DECLARE_METHOD(10)
		J2CPP_DECLARE_METHOD(11)
		J2CPP_DECLARE_METHOD(12)
		J2CPP_DECLARE_METHOD(13)
		J2CPP_DECLARE_METHOD(14)
		J2CPP_DECLARE_METHOD(15)
		J2CPP_DECLARE_METHOD(16)
		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)
		J2CPP_DECLARE_FIELD(2)
		J2CPP_DECLARE_FIELD(3)

		TestResult(jobject jobj)
		: cpp_object<TestResult>(jobj)
		{
		}

		void addError(local_ref< junit::framework::Test > const&, local_ref< java::lang::Throwable > const&);
		void addFailure(local_ref< junit::framework::Test > const&, local_ref< junit::framework::AssertionFailedError > const&);
		void addListener(local_ref< junit::framework::TestListener > const&);
		void removeListener(local_ref< junit::framework::TestListener > const&);
		void endTest(local_ref< junit::framework::Test > const&);
		cpp_int errorCount();
		local_ref< java::util::Enumeration > errors();
		cpp_int failureCount();
		local_ref< java::util::Enumeration > failures();
		cpp_int runCount();
		void runProtected(local_ref< junit::framework::Test > const&, local_ref< junit::framework::Protectable > const&);
		cpp_boolean shouldStop();
		void startTest(local_ref< junit::framework::Test > const&);
		void stop();
		cpp_boolean wasSuccessful();

	}; //class TestResult

} //namespace framework
} //namespace junit


} //namespace j2cpp

#endif //J2CPP_JUNIT_FRAMEWORK_TESTRESULT_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JUNIT_FRAMEWORK_TESTRESULT_HPP_IMPL
#define J2CPP_JUNIT_FRAMEWORK_TESTRESULT_HPP_IMPL

namespace j2cpp {


template <>
local_ref< junit::framework::TestResult > create< junit::framework::TestResult>()
{
	return local_ref< junit::framework::TestResult >(
		environment::get().get_jenv()->NewObject(
			get_class<junit::framework::TestResult::J2CPP_CLASS_NAME>(),
			get_method_id<junit::framework::TestResult::J2CPP_CLASS_NAME, junit::framework::TestResult::J2CPP_METHOD_NAME(0), junit::framework::TestResult::J2CPP_METHOD_SIGNATURE(0), false>()
		)
	);
}

void junit::framework::TestResult::addError(local_ref< junit::framework::Test > const &a0, local_ref< java::lang::Throwable > const &a1)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(1), J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

void junit::framework::TestResult::addFailure(local_ref< junit::framework::Test > const &a0, local_ref< junit::framework::AssertionFailedError > const &a1)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(2), J2CPP_METHOD_SIGNATURE(2), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

void junit::framework::TestResult::addListener(local_ref< junit::framework::TestListener > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(3), J2CPP_METHOD_SIGNATURE(3), false>(),
			a0.get_jtype()
		)
	);
}

void junit::framework::TestResult::removeListener(local_ref< junit::framework::TestListener > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(4), J2CPP_METHOD_SIGNATURE(4), false>(),
			a0.get_jtype()
		)
	);
}

void junit::framework::TestResult::endTest(local_ref< junit::framework::Test > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(5), J2CPP_METHOD_SIGNATURE(5), false>(),
			a0.get_jtype()
		)
	);
}

cpp_int junit::framework::TestResult::errorCount()
{
	return cpp_int(
		environment::get().get_jenv()->CallIntMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(6), J2CPP_METHOD_SIGNATURE(6), false>()
		)
	);
}

local_ref< java::util::Enumeration > junit::framework::TestResult::errors()
{
	return local_ref< java::util::Enumeration >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(7), J2CPP_METHOD_SIGNATURE(7), false>()
		)
	);
}

cpp_int junit::framework::TestResult::failureCount()
{
	return cpp_int(
		environment::get().get_jenv()->CallIntMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(8), J2CPP_METHOD_SIGNATURE(8), false>()
		)
	);
}

local_ref< java::util::Enumeration > junit::framework::TestResult::failures()
{
	return local_ref< java::util::Enumeration >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(9), J2CPP_METHOD_SIGNATURE(9), false>()
		)
	);
}


cpp_int junit::framework::TestResult::runCount()
{
	return cpp_int(
		environment::get().get_jenv()->CallIntMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(11), J2CPP_METHOD_SIGNATURE(11), false>()
		)
	);
}

void junit::framework::TestResult::runProtected(local_ref< junit::framework::Test > const &a0, local_ref< junit::framework::Protectable > const &a1)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(12), J2CPP_METHOD_SIGNATURE(12), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

cpp_boolean junit::framework::TestResult::shouldStop()
{
	return cpp_boolean(
		environment::get().get_jenv()->CallBooleanMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(13), J2CPP_METHOD_SIGNATURE(13), false>()
		)
	);
}

void junit::framework::TestResult::startTest(local_ref< junit::framework::Test > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(14), J2CPP_METHOD_SIGNATURE(14), false>(),
			a0.get_jtype()
		)
	);
}

void junit::framework::TestResult::stop()
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(15), J2CPP_METHOD_SIGNATURE(15), false>()
		)
	);
}

cpp_boolean junit::framework::TestResult::wasSuccessful()
{
	return cpp_boolean(
		environment::get().get_jenv()->CallBooleanMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(16), J2CPP_METHOD_SIGNATURE(16), false>()
		)
	);
}



J2CPP_DEFINE_CLASS(junit::framework::TestResult,"junit/framework/TestResult")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,0,"<init>","()V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,1,"addError","(Ljunit/framework/Test;Ljava/lang/Throwable;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,2,"addFailure","(Ljunit/framework/Test;Ljunit/framework/AssertionFailedError;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,3,"addListener","(Ljunit/framework/TestListener;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,4,"removeListener","(Ljunit/framework/TestListener;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,5,"endTest","(Ljunit/framework/Test;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,6,"errorCount","()I")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,7,"errors","()Ljava/util/Enumeration;")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,8,"failureCount","()I")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,9,"failures","()Ljava/util/Enumeration;")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,10,"run","(Ljunit/framework/TestCase;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,11,"runCount","()I")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,12,"runProtected","(Ljunit/framework/Test;Ljunit/framework/Protectable;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,13,"shouldStop","()Z")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,14,"startTest","(Ljunit/framework/Test;)V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,15,"stop","()V")
J2CPP_DEFINE_METHOD(junit::framework::TestResult,16,"wasSuccessful","()Z")
J2CPP_DEFINE_FIELD(junit::framework::TestResult,0,"fFailures","Ljava/util/Vector;")
J2CPP_DEFINE_FIELD(junit::framework::TestResult,1,"fErrors","Ljava/util/Vector;")
J2CPP_DEFINE_FIELD(junit::framework::TestResult,2,"fListeners","Ljava/util/Vector;")
J2CPP_DEFINE_FIELD(junit::framework::TestResult,3,"fRunTests","I")

} //namespace j2cpp

#endif //J2CPP_JUNIT_FRAMEWORK_TESTRESULT_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
