/*================================================================================
  code generated by: java2cpp
  class: android.text.method.DigitsKeyListener
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_TEXT_METHOD_DIGITSKEYLISTENER_HPP_DECL
#define J2CPP_ANDROID_TEXT_METHOD_DIGITSKEYLISTENER_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class CharSequence; } } }
namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace android { namespace text { namespace method { class NumberKeyListener; } } } }
namespace j2cpp { namespace android { namespace text { class Spanned; } } }


#include <android/text/Spanned.hpp>
#include <android/text/method/NumberKeyListener.hpp>
#include <java/lang/CharSequence.hpp>
#include <java/lang/String.hpp>


namespace j2cpp {

namespace android { namespace text { namespace method {

	class DigitsKeyListener;
	class DigitsKeyListener
		: public cpp_object<DigitsKeyListener>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)
		J2CPP_DECLARE_METHOD(6)
		J2CPP_DECLARE_METHOD(7)

		explicit DigitsKeyListener(jobject jobj)
		: cpp_object<DigitsKeyListener>(jobj)
		{
		}

		operator local_ref<android::text::method::NumberKeyListener>() const;


		DigitsKeyListener();
		DigitsKeyListener(cpp_boolean const&, cpp_boolean const&);
		static local_ref< android::text::method::DigitsKeyListener > getInstance();
		static local_ref< android::text::method::DigitsKeyListener > getInstance(cpp_boolean const&, cpp_boolean const&);
		static local_ref< android::text::method::DigitsKeyListener > getInstance(local_ref< java::lang::String > const&);
		cpp_int getInputType();
		local_ref< java::lang::CharSequence > filter(local_ref< java::lang::CharSequence > const&, cpp_int const&, cpp_int const&, local_ref< android::text::Spanned > const&, cpp_int const&, cpp_int const&);
	}; //class DigitsKeyListener

} //namespace method
} //namespace text
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_TEXT_METHOD_DIGITSKEYLISTENER_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_TEXT_METHOD_DIGITSKEYLISTENER_HPP_IMPL
#define J2CPP_ANDROID_TEXT_METHOD_DIGITSKEYLISTENER_HPP_IMPL

namespace j2cpp {



android::text::method::DigitsKeyListener::operator local_ref<android::text::method::NumberKeyListener>() const
{
	return local_ref<android::text::method::NumberKeyListener>(get_jtype());
}


android::text::method::DigitsKeyListener::DigitsKeyListener()
: cpp_object<android::text::method::DigitsKeyListener>(
	environment::get().get_jenv()->NewObject(
		get_class<android::text::method::DigitsKeyListener::J2CPP_CLASS_NAME>(),
		get_method_id<android::text::method::DigitsKeyListener::J2CPP_CLASS_NAME, android::text::method::DigitsKeyListener::J2CPP_METHOD_NAME(0), android::text::method::DigitsKeyListener::J2CPP_METHOD_SIGNATURE(0), false>()
	)
)
{
}



android::text::method::DigitsKeyListener::DigitsKeyListener(cpp_boolean const &a0, cpp_boolean const &a1)
: cpp_object<android::text::method::DigitsKeyListener>(
	environment::get().get_jenv()->NewObject(
		get_class<android::text::method::DigitsKeyListener::J2CPP_CLASS_NAME>(),
		get_method_id<android::text::method::DigitsKeyListener::J2CPP_CLASS_NAME, android::text::method::DigitsKeyListener::J2CPP_METHOD_NAME(1), android::text::method::DigitsKeyListener::J2CPP_METHOD_SIGNATURE(1), false>(),
		a0.get_jtype(), a1.get_jtype()
	)
)
{
}



local_ref< android::text::method::DigitsKeyListener > android::text::method::DigitsKeyListener::getInstance()
{
	return local_ref< android::text::method::DigitsKeyListener >(
		environment::get().get_jenv()->CallStaticObjectMethod(
			get_class<J2CPP_CLASS_NAME>(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(3), J2CPP_METHOD_SIGNATURE(3), true>()
		)
	);
}

local_ref< android::text::method::DigitsKeyListener > android::text::method::DigitsKeyListener::getInstance(cpp_boolean const &a0, cpp_boolean const &a1)
{
	return local_ref< android::text::method::DigitsKeyListener >(
		environment::get().get_jenv()->CallStaticObjectMethod(
			get_class<J2CPP_CLASS_NAME>(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(4), J2CPP_METHOD_SIGNATURE(4), true>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

local_ref< android::text::method::DigitsKeyListener > android::text::method::DigitsKeyListener::getInstance(local_ref< java::lang::String > const &a0)
{
	return local_ref< android::text::method::DigitsKeyListener >(
		environment::get().get_jenv()->CallStaticObjectMethod(
			get_class<J2CPP_CLASS_NAME>(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(5), J2CPP_METHOD_SIGNATURE(5), true>(),
			a0.get_jtype()
		)
	);
}

cpp_int android::text::method::DigitsKeyListener::getInputType()
{
	return cpp_int(
		environment::get().get_jenv()->CallIntMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(6), J2CPP_METHOD_SIGNATURE(6), false>()
		)
	);
}

local_ref< java::lang::CharSequence > android::text::method::DigitsKeyListener::filter(local_ref< java::lang::CharSequence > const &a0, cpp_int const &a1, cpp_int const &a2, local_ref< android::text::Spanned > const &a3, cpp_int const &a4, cpp_int const &a5)
{
	return local_ref< java::lang::CharSequence >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(7), J2CPP_METHOD_SIGNATURE(7), false>(),
			a0.get_jtype(), a1.get_jtype(), a2.get_jtype(), a3.get_jtype(), a4.get_jtype(), a5.get_jtype()
		)
	);
}


J2CPP_DEFINE_CLASS(android::text::method::DigitsKeyListener,"android/text/method/DigitsKeyListener")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,0,"<init>","()V")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,1,"<init>","(ZZ)V")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,2,"getAcceptedChars","()[C")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,3,"getInstance","()Landroid/text/method/DigitsKeyListener;")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,4,"getInstance","(ZZ)Landroid/text/method/DigitsKeyListener;")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,5,"getInstance","(Ljava/lang/String;)Landroid/text/method/DigitsKeyListener;")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,6,"getInputType","()I")
J2CPP_DEFINE_METHOD(android::text::method::DigitsKeyListener,7,"filter","(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")

} //namespace j2cpp

#endif //J2CPP_ANDROID_TEXT_METHOD_DIGITSKEYLISTENER_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
