/*================================================================================
  code generated by: java2cpp
  class: java.lang.ClassNotFoundException
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_LANG_CLASSNOTFOUNDEXCEPTION_HPP_DECL
#define J2CPP_JAVA_LANG_CLASSNOTFOUNDEXCEPTION_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace lang { class Throwable; } } }


#include <java/lang/String.hpp>
#include <java/lang/Throwable.hpp>


namespace j2cpp {

namespace java { namespace lang {

	class ClassNotFoundException;
	class ClassNotFoundException
		: public cpp_object<ClassNotFoundException>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)

		ClassNotFoundException(jobject jobj)
		: cpp_object<ClassNotFoundException>(jobj)
		{
		}

		local_ref< java::lang::Throwable > getException();
		local_ref< java::lang::Throwable > getCause();
	}; //class ClassNotFoundException

} //namespace lang
} //namespace java


} //namespace j2cpp

#endif //J2CPP_JAVA_LANG_CLASSNOTFOUNDEXCEPTION_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_LANG_CLASSNOTFOUNDEXCEPTION_HPP_IMPL
#define J2CPP_JAVA_LANG_CLASSNOTFOUNDEXCEPTION_HPP_IMPL

namespace j2cpp {


template <>
local_ref< java::lang::ClassNotFoundException > create< java::lang::ClassNotFoundException>()
{
	return local_ref< java::lang::ClassNotFoundException >(
		environment::get().get_jenv()->NewObject(
			get_class<java::lang::ClassNotFoundException::J2CPP_CLASS_NAME>(),
			get_method_id<java::lang::ClassNotFoundException::J2CPP_CLASS_NAME, java::lang::ClassNotFoundException::J2CPP_METHOD_NAME(0), java::lang::ClassNotFoundException::J2CPP_METHOD_SIGNATURE(0), false>()
		)
	);
}

template <>
local_ref< java::lang::ClassNotFoundException > create< java::lang::ClassNotFoundException>(local_ref< java::lang::String > const &a0)
{
	return local_ref< java::lang::ClassNotFoundException >(
		environment::get().get_jenv()->NewObject(
			get_class<java::lang::ClassNotFoundException::J2CPP_CLASS_NAME>(),
			get_method_id<java::lang::ClassNotFoundException::J2CPP_CLASS_NAME, java::lang::ClassNotFoundException::J2CPP_METHOD_NAME(1), java::lang::ClassNotFoundException::J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype()
		)
	);
}

template <>
local_ref< java::lang::ClassNotFoundException > create< java::lang::ClassNotFoundException>(local_ref< java::lang::String > const &a0, local_ref< java::lang::Throwable > const &a1)
{
	return local_ref< java::lang::ClassNotFoundException >(
		environment::get().get_jenv()->NewObject(
			get_class<java::lang::ClassNotFoundException::J2CPP_CLASS_NAME>(),
			get_method_id<java::lang::ClassNotFoundException::J2CPP_CLASS_NAME, java::lang::ClassNotFoundException::J2CPP_METHOD_NAME(2), java::lang::ClassNotFoundException::J2CPP_METHOD_SIGNATURE(2), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

local_ref< java::lang::Throwable > java::lang::ClassNotFoundException::getException()
{
	return local_ref< java::lang::Throwable >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(3), J2CPP_METHOD_SIGNATURE(3), false>()
		)
	);
}

local_ref< java::lang::Throwable > java::lang::ClassNotFoundException::getCause()
{
	return local_ref< java::lang::Throwable >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(4), J2CPP_METHOD_SIGNATURE(4), false>()
		)
	);
}


J2CPP_DEFINE_CLASS(java::lang::ClassNotFoundException,"java/lang/ClassNotFoundException")
J2CPP_DEFINE_METHOD(java::lang::ClassNotFoundException,0,"<init>","()V")
J2CPP_DEFINE_METHOD(java::lang::ClassNotFoundException,1,"<init>","(Ljava/lang/String;)V")
J2CPP_DEFINE_METHOD(java::lang::ClassNotFoundException,2,"<init>","(Ljava/lang/String;Ljava/lang/Throwable;)V")
J2CPP_DEFINE_METHOD(java::lang::ClassNotFoundException,3,"getException","()Ljava/lang/Throwable;")
J2CPP_DEFINE_METHOD(java::lang::ClassNotFoundException,4,"getCause","()Ljava/lang/Throwable;")

} //namespace j2cpp

#endif //J2CPP_JAVA_LANG_CLASSNOTFOUNDEXCEPTION_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
