/*================================================================================
  code generated by: java2cpp
  class: java.lang.UnsatisfiedLinkError
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_LANG_UNSATISFIEDLINKERROR_HPP_DECL
#define J2CPP_JAVA_LANG_UNSATISFIEDLINKERROR_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }


#include <java/lang/String.hpp>


namespace j2cpp {

namespace java { namespace lang {

	class UnsatisfiedLinkError;
	class UnsatisfiedLinkError
		: public cpp_object<UnsatisfiedLinkError>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)

		UnsatisfiedLinkError(jobject jobj)
		: cpp_object<UnsatisfiedLinkError>(jobj)
		{
		}

	}; //class UnsatisfiedLinkError

} //namespace lang
} //namespace java


} //namespace j2cpp

#endif //J2CPP_JAVA_LANG_UNSATISFIEDLINKERROR_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_LANG_UNSATISFIEDLINKERROR_HPP_IMPL
#define J2CPP_JAVA_LANG_UNSATISFIEDLINKERROR_HPP_IMPL

namespace j2cpp {


template <>
local_ref< java::lang::UnsatisfiedLinkError > create< java::lang::UnsatisfiedLinkError>()
{
	return local_ref< java::lang::UnsatisfiedLinkError >(
		environment::get().get_jenv()->NewObject(
			get_class<java::lang::UnsatisfiedLinkError::J2CPP_CLASS_NAME>(),
			get_method_id<java::lang::UnsatisfiedLinkError::J2CPP_CLASS_NAME, java::lang::UnsatisfiedLinkError::J2CPP_METHOD_NAME(0), java::lang::UnsatisfiedLinkError::J2CPP_METHOD_SIGNATURE(0), false>()
		)
	);
}

template <>
local_ref< java::lang::UnsatisfiedLinkError > create< java::lang::UnsatisfiedLinkError>(local_ref< java::lang::String > const &a0)
{
	return local_ref< java::lang::UnsatisfiedLinkError >(
		environment::get().get_jenv()->NewObject(
			get_class<java::lang::UnsatisfiedLinkError::J2CPP_CLASS_NAME>(),
			get_method_id<java::lang::UnsatisfiedLinkError::J2CPP_CLASS_NAME, java::lang::UnsatisfiedLinkError::J2CPP_METHOD_NAME(1), java::lang::UnsatisfiedLinkError::J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype()
		)
	);
}


J2CPP_DEFINE_CLASS(java::lang::UnsatisfiedLinkError,"java/lang/UnsatisfiedLinkError")
J2CPP_DEFINE_METHOD(java::lang::UnsatisfiedLinkError,0,"<init>","()V")
J2CPP_DEFINE_METHOD(java::lang::UnsatisfiedLinkError,1,"<init>","(Ljava/lang/String;)V")

} //namespace j2cpp

#endif //J2CPP_JAVA_LANG_UNSATISFIEDLINKERROR_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
