/*================================================================================
  code generated by: java2cpp
  class: java.util.FormatFlagsConversionMismatchException
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_UTIL_FORMATFLAGSCONVERSIONMISMATCHEXCEPTION_HPP_DECL
#define J2CPP_JAVA_UTIL_FORMATFLAGSCONVERSIONMISMATCHEXCEPTION_HPP_DECL


namespace j2cpp { namespace java { namespace io { class Serializable; } } }
namespace j2cpp { namespace java { namespace lang { class String; } } }
namespace j2cpp { namespace java { namespace util { class IllegalFormatException; } } }


#include <java/io/Serializable.hpp>
#include <java/lang/String.hpp>
#include <java/util/IllegalFormatException.hpp>


namespace j2cpp {

namespace java { namespace util {

	class FormatFlagsConversionMismatchException;
	class FormatFlagsConversionMismatchException
		: public cpp_object<FormatFlagsConversionMismatchException>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)

		explicit FormatFlagsConversionMismatchException(jobject jobj)
		: cpp_object<FormatFlagsConversionMismatchException>(jobj)
		{
		}

		operator local_ref<java::util::IllegalFormatException>() const;
		operator local_ref<java::io::Serializable>() const;


		FormatFlagsConversionMismatchException(local_ref< java::lang::String > const&, cpp_char const&);
		local_ref< java::lang::String > getFlags();
		cpp_char getConversion();
		local_ref< java::lang::String > getMessage();
	}; //class FormatFlagsConversionMismatchException

} //namespace util
} //namespace java

} //namespace j2cpp

#endif //J2CPP_JAVA_UTIL_FORMATFLAGSCONVERSIONMISMATCHEXCEPTION_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_UTIL_FORMATFLAGSCONVERSIONMISMATCHEXCEPTION_HPP_IMPL
#define J2CPP_JAVA_UTIL_FORMATFLAGSCONVERSIONMISMATCHEXCEPTION_HPP_IMPL

namespace j2cpp {



java::util::FormatFlagsConversionMismatchException::operator local_ref<java::util::IllegalFormatException>() const
{
	return local_ref<java::util::IllegalFormatException>(get_jtype());
}

java::util::FormatFlagsConversionMismatchException::operator local_ref<java::io::Serializable>() const
{
	return local_ref<java::io::Serializable>(get_jtype());
}


java::util::FormatFlagsConversionMismatchException::FormatFlagsConversionMismatchException(local_ref< java::lang::String > const &a0, cpp_char const &a1)
: cpp_object<java::util::FormatFlagsConversionMismatchException>(
	environment::get().get_jenv()->NewObject(
		get_class<java::util::FormatFlagsConversionMismatchException::J2CPP_CLASS_NAME>(),
		get_method_id<java::util::FormatFlagsConversionMismatchException::J2CPP_CLASS_NAME, java::util::FormatFlagsConversionMismatchException::J2CPP_METHOD_NAME(0), java::util::FormatFlagsConversionMismatchException::J2CPP_METHOD_SIGNATURE(0), false>(),
		a0.get_jtype(), a1.get_jtype()
	)
)
{
}


local_ref< java::lang::String > java::util::FormatFlagsConversionMismatchException::getFlags()
{
	return local_ref< java::lang::String >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(1), J2CPP_METHOD_SIGNATURE(1), false>()
		)
	);
}

cpp_char java::util::FormatFlagsConversionMismatchException::getConversion()
{
	return cpp_char(
		environment::get().get_jenv()->CallCharMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(2), J2CPP_METHOD_SIGNATURE(2), false>()
		)
	);
}

local_ref< java::lang::String > java::util::FormatFlagsConversionMismatchException::getMessage()
{
	return local_ref< java::lang::String >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(3), J2CPP_METHOD_SIGNATURE(3), false>()
		)
	);
}


J2CPP_DEFINE_CLASS(java::util::FormatFlagsConversionMismatchException,"java/util/FormatFlagsConversionMismatchException")
J2CPP_DEFINE_METHOD(java::util::FormatFlagsConversionMismatchException,0,"<init>","(Ljava/lang/String;C)V")
J2CPP_DEFINE_METHOD(java::util::FormatFlagsConversionMismatchException,1,"getFlags","()Ljava/lang/String;")
J2CPP_DEFINE_METHOD(java::util::FormatFlagsConversionMismatchException,2,"getConversion","()C")
J2CPP_DEFINE_METHOD(java::util::FormatFlagsConversionMismatchException,3,"getMessage","()Ljava/lang/String;")

} //namespace j2cpp

#endif //J2CPP_JAVA_UTIL_FORMATFLAGSCONVERSIONMISMATCHEXCEPTION_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
