/*================================================================================
  code generated by: java2cpp
  class: android.database.StaleDataException
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_DATABASE_STALEDATAEXCEPTION_HPP_DECL
#define J2CPP_ANDROID_DATABASE_STALEDATAEXCEPTION_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class String; } } }


#include <java/lang/String.hpp>


namespace j2cpp {

namespace android { namespace database {

	class StaleDataException;
	class StaleDataException
		: public cpp_object<StaleDataException>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)

		StaleDataException(jobject jobj)
		: cpp_object<StaleDataException>(jobj)
		{
		}

	}; //class StaleDataException

} //namespace database
} //namespace android


} //namespace j2cpp

#endif //J2CPP_ANDROID_DATABASE_STALEDATAEXCEPTION_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_DATABASE_STALEDATAEXCEPTION_HPP_IMPL
#define J2CPP_ANDROID_DATABASE_STALEDATAEXCEPTION_HPP_IMPL

namespace j2cpp {


template <>
local_ref< android::database::StaleDataException > create< android::database::StaleDataException>()
{
	return local_ref< android::database::StaleDataException >(
		environment::get().get_jenv()->NewObject(
			get_class<android::database::StaleDataException::J2CPP_CLASS_NAME>(),
			get_method_id<android::database::StaleDataException::J2CPP_CLASS_NAME, android::database::StaleDataException::J2CPP_METHOD_NAME(0), android::database::StaleDataException::J2CPP_METHOD_SIGNATURE(0), false>()
		)
	);
}

template <>
local_ref< android::database::StaleDataException > create< android::database::StaleDataException>(local_ref< java::lang::String > const &a0)
{
	return local_ref< android::database::StaleDataException >(
		environment::get().get_jenv()->NewObject(
			get_class<android::database::StaleDataException::J2CPP_CLASS_NAME>(),
			get_method_id<android::database::StaleDataException::J2CPP_CLASS_NAME, android::database::StaleDataException::J2CPP_METHOD_NAME(1), android::database::StaleDataException::J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype()
		)
	);
}


J2CPP_DEFINE_CLASS(android::database::StaleDataException,"android/database/StaleDataException")
J2CPP_DEFINE_METHOD(android::database::StaleDataException,0,"<init>","()V")
J2CPP_DEFINE_METHOD(android::database::StaleDataException,1,"<init>","(Ljava/lang/String;)V")

} //namespace j2cpp

#endif //J2CPP_ANDROID_DATABASE_STALEDATAEXCEPTION_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
