/*================================================================================
  code generated by: java2cpp
  class: android.text.NoCopySpan
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_TEXT_NOCOPYSPAN_HPP_DECL
#define J2CPP_ANDROID_TEXT_NOCOPYSPAN_HPP_DECL


namespace j2cpp { namespace java { namespace lang { class Object; } } }


#include <java/lang/Object.hpp>


namespace j2cpp {

namespace android { namespace text {

	class NoCopySpan;
	namespace NoCopySpan_ {

		class Concrete;
		class Concrete
			: public cpp_object<Concrete>
		{
		public:

			J2CPP_DECLARE_CLASS

			J2CPP_DECLARE_METHOD(0)

			explicit Concrete(jobject jobj)
			: cpp_object<Concrete>(jobj)
			{
			}

			operator local_ref<java::lang::Object>() const;
			operator local_ref<android::text::NoCopySpan>() const;


			Concrete();
		}; //class Concrete

	} //namespace NoCopySpan_

	class NoCopySpan
		: public cpp_object<NoCopySpan>
	{
	public:

		J2CPP_DECLARE_CLASS


		typedef NoCopySpan_::Concrete Concrete;

		explicit NoCopySpan(jobject jobj)
		: cpp_object<NoCopySpan>(jobj)
		{
		}

		operator local_ref<java::lang::Object>() const;

	}; //class NoCopySpan

} //namespace text
} //namespace android

} //namespace j2cpp

#endif //J2CPP_ANDROID_TEXT_NOCOPYSPAN_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_TEXT_NOCOPYSPAN_HPP_IMPL
#define J2CPP_ANDROID_TEXT_NOCOPYSPAN_HPP_IMPL

namespace j2cpp {




android::text::NoCopySpan_::Concrete::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jtype());
}

android::text::NoCopySpan_::Concrete::operator local_ref<android::text::NoCopySpan>() const
{
	return local_ref<android::text::NoCopySpan>(get_jtype());
}


android::text::NoCopySpan_::Concrete::Concrete()
: cpp_object<android::text::NoCopySpan_::Concrete>(
	environment::get().get_jenv()->NewObject(
		get_class<android::text::NoCopySpan_::Concrete::J2CPP_CLASS_NAME>(),
		get_method_id<android::text::NoCopySpan_::Concrete::J2CPP_CLASS_NAME, android::text::NoCopySpan_::Concrete::J2CPP_METHOD_NAME(0), android::text::NoCopySpan_::Concrete::J2CPP_METHOD_SIGNATURE(0), false>()
	)
)
{
}



J2CPP_DEFINE_CLASS(android::text::NoCopySpan_::Concrete,"android/text/NoCopySpan$Concrete")
J2CPP_DEFINE_METHOD(android::text::NoCopySpan_::Concrete,0,"<init>","()V")



android::text::NoCopySpan::operator local_ref<java::lang::Object>() const
{
	return local_ref<java::lang::Object>(get_jtype());
}

J2CPP_DEFINE_CLASS(android::text::NoCopySpan,"android/text/NoCopySpan")

} //namespace j2cpp

#endif //J2CPP_ANDROID_TEXT_NOCOPYSPAN_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
