/*================================================================================
  code generated by: java2cpp
  class: java.io.OptionalDataException
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_IO_OPTIONALDATAEXCEPTION_HPP_DECL
#define J2CPP_JAVA_IO_OPTIONALDATAEXCEPTION_HPP_DECL






namespace j2cpp {

namespace java { namespace io {

	class OptionalDataException;
	class OptionalDataException
		: public cpp_object<OptionalDataException>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_FIELD(0)
		J2CPP_DECLARE_FIELD(1)

		OptionalDataException(jobject jobj)
		: cpp_object<OptionalDataException>(jobj)
		, eof(jobj)
		, length(jobj)
		{
		}


		field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(0), J2CPP_FIELD_SIGNATURE(0), cpp_boolean > eof;
		field< J2CPP_CLASS_NAME, J2CPP_FIELD_NAME(1), J2CPP_FIELD_SIGNATURE(1), cpp_int > length;
	}; //class OptionalDataException

} //namespace io
} //namespace java


} //namespace j2cpp

#endif //J2CPP_JAVA_IO_OPTIONALDATAEXCEPTION_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_IO_OPTIONALDATAEXCEPTION_HPP_IMPL
#define J2CPP_JAVA_IO_OPTIONALDATAEXCEPTION_HPP_IMPL

namespace j2cpp {


template <>
local_ref< java::io::OptionalDataException > create< java::io::OptionalDataException>()
{
	return local_ref< java::io::OptionalDataException >(
		environment::get().get_jenv()->NewObject(
			get_class<java::io::OptionalDataException::J2CPP_CLASS_NAME>(),
			get_method_id<java::io::OptionalDataException::J2CPP_CLASS_NAME, java::io::OptionalDataException::J2CPP_METHOD_NAME(0), java::io::OptionalDataException::J2CPP_METHOD_SIGNATURE(0), false>()
		)
	);
}



J2CPP_DEFINE_CLASS(java::io::OptionalDataException,"java/io/OptionalDataException")
J2CPP_DEFINE_METHOD(java::io::OptionalDataException,0,"<init>","()V")
J2CPP_DEFINE_FIELD(java::io::OptionalDataException,0,"eof","Z")
J2CPP_DEFINE_FIELD(java::io::OptionalDataException,1,"length","I")

} //namespace j2cpp

#endif //J2CPP_JAVA_IO_OPTIONALDATAEXCEPTION_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
