/*================================================================================
  code generated by: java2cpp
  class: java.util.EventListener
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_UTIL_EVENTLISTENER_HPP_DECL
#define J2CPP_JAVA_UTIL_EVENTLISTENER_HPP_DECL






namespace j2cpp {

namespace java { namespace util {

	class EventListener;
	class EventListener
		: public cpp_object<EventListener>
	{
	public:

		J2CPP_DECLARE_CLASS


		EventListener(jobject jobj)
		: cpp_object<EventListener>(jobj)
		{
		}
	}; //class EventListener

} //namespace util
} //namespace java


} //namespace j2cpp

#endif //J2CPP_JAVA_UTIL_EVENTLISTENER_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_JAVA_UTIL_EVENTLISTENER_HPP_IMPL
#define J2CPP_JAVA_UTIL_EVENTLISTENER_HPP_IMPL

namespace j2cpp {


J2CPP_DEFINE_CLASS(java::util::EventListener,"java/util/EventListener")

} //namespace j2cpp

#endif //J2CPP_JAVA_UTIL_EVENTLISTENER_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
