/*================================================================================
  code generated by: java2cpp
  class: org.apache.http.message.BasicHttpEntityEnclosingRequest
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_MESSAGE_BASICHTTPENTITYENCLOSINGREQUEST_HPP_DECL
#define J2CPP_ORG_APACHE_HTTP_MESSAGE_BASICHTTPENTITYENCLOSINGREQUEST_HPP_DECL


namespace j2cpp { namespace org { namespace apache { namespace http { class HttpEntity; } } } }
namespace j2cpp { namespace org { namespace apache { namespace http { class ProtocolVersion; } } } }
namespace j2cpp { namespace org { namespace apache { namespace http { class RequestLine; } } } }
namespace j2cpp { namespace java { namespace lang { class String; } } }


#include <java/lang/String.hpp>
#include <org/apache/http/HttpEntity.hpp>
#include <org/apache/http/ProtocolVersion.hpp>
#include <org/apache/http/RequestLine.hpp>


namespace j2cpp {

namespace org { namespace apache { namespace http { namespace message {

	class BasicHttpEntityEnclosingRequest;
	class BasicHttpEntityEnclosingRequest
		: public cpp_object<BasicHttpEntityEnclosingRequest>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)
		J2CPP_DECLARE_METHOD(1)
		J2CPP_DECLARE_METHOD(2)
		J2CPP_DECLARE_METHOD(3)
		J2CPP_DECLARE_METHOD(4)
		J2CPP_DECLARE_METHOD(5)

		BasicHttpEntityEnclosingRequest(jobject jobj)
		: cpp_object<BasicHttpEntityEnclosingRequest>(jobj)
		{
		}

		local_ref< org::apache::http::HttpEntity > getEntity();
		void setEntity(local_ref< org::apache::http::HttpEntity > const&);
		cpp_boolean expectContinue();
	}; //class BasicHttpEntityEnclosingRequest

} //namespace message
} //namespace http
} //namespace apache
} //namespace org


} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_MESSAGE_BASICHTTPENTITYENCLOSINGREQUEST_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ORG_APACHE_HTTP_MESSAGE_BASICHTTPENTITYENCLOSINGREQUEST_HPP_IMPL
#define J2CPP_ORG_APACHE_HTTP_MESSAGE_BASICHTTPENTITYENCLOSINGREQUEST_HPP_IMPL

namespace j2cpp {


template <>
local_ref< org::apache::http::message::BasicHttpEntityEnclosingRequest > create< org::apache::http::message::BasicHttpEntityEnclosingRequest>(local_ref< java::lang::String > const &a0, local_ref< java::lang::String > const &a1)
{
	return local_ref< org::apache::http::message::BasicHttpEntityEnclosingRequest >(
		environment::get().get_jenv()->NewObject(
			get_class<org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_CLASS_NAME>(),
			get_method_id<org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_CLASS_NAME, org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_METHOD_NAME(0), org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_METHOD_SIGNATURE(0), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}

template <>
local_ref< org::apache::http::message::BasicHttpEntityEnclosingRequest > create< org::apache::http::message::BasicHttpEntityEnclosingRequest>(local_ref< java::lang::String > const &a0, local_ref< java::lang::String > const &a1, local_ref< org::apache::http::ProtocolVersion > const &a2)
{
	return local_ref< org::apache::http::message::BasicHttpEntityEnclosingRequest >(
		environment::get().get_jenv()->NewObject(
			get_class<org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_CLASS_NAME>(),
			get_method_id<org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_CLASS_NAME, org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_METHOD_NAME(1), org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_METHOD_SIGNATURE(1), false>(),
			a0.get_jtype(), a1.get_jtype(), a2.get_jtype()
		)
	);
}

template <>
local_ref< org::apache::http::message::BasicHttpEntityEnclosingRequest > create< org::apache::http::message::BasicHttpEntityEnclosingRequest>(local_ref< org::apache::http::RequestLine > const &a0)
{
	return local_ref< org::apache::http::message::BasicHttpEntityEnclosingRequest >(
		environment::get().get_jenv()->NewObject(
			get_class<org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_CLASS_NAME>(),
			get_method_id<org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_CLASS_NAME, org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_METHOD_NAME(2), org::apache::http::message::BasicHttpEntityEnclosingRequest::J2CPP_METHOD_SIGNATURE(2), false>(),
			a0.get_jtype()
		)
	);
}

local_ref< org::apache::http::HttpEntity > org::apache::http::message::BasicHttpEntityEnclosingRequest::getEntity()
{
	return local_ref< org::apache::http::HttpEntity >(
		environment::get().get_jenv()->CallObjectMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(3), J2CPP_METHOD_SIGNATURE(3), false>()
		)
	);
}

void org::apache::http::message::BasicHttpEntityEnclosingRequest::setEntity(local_ref< org::apache::http::HttpEntity > const &a0)
{
	return void(
		environment::get().get_jenv()->CallVoidMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(4), J2CPP_METHOD_SIGNATURE(4), false>(),
			a0.get_jtype()
		)
	);
}

cpp_boolean org::apache::http::message::BasicHttpEntityEnclosingRequest::expectContinue()
{
	return cpp_boolean(
		environment::get().get_jenv()->CallBooleanMethod(
			get_jtype(),
			get_method_id<J2CPP_CLASS_NAME, J2CPP_METHOD_NAME(5), J2CPP_METHOD_SIGNATURE(5), false>()
		)
	);
}


J2CPP_DEFINE_CLASS(org::apache::http::message::BasicHttpEntityEnclosingRequest,"org/apache/http/message/BasicHttpEntityEnclosingRequest")
J2CPP_DEFINE_METHOD(org::apache::http::message::BasicHttpEntityEnclosingRequest,0,"<init>","(Ljava/lang/String;Ljava/lang/String;)V")
J2CPP_DEFINE_METHOD(org::apache::http::message::BasicHttpEntityEnclosingRequest,1,"<init>","(Ljava/lang/String;Ljava/lang/String;Lorg/apache/http/ProtocolVersion;)V")
J2CPP_DEFINE_METHOD(org::apache::http::message::BasicHttpEntityEnclosingRequest,2,"<init>","(Lorg/apache/http/RequestLine;)V")
J2CPP_DEFINE_METHOD(org::apache::http::message::BasicHttpEntityEnclosingRequest,3,"getEntity","()Lorg/apache/http/HttpEntity;")
J2CPP_DEFINE_METHOD(org::apache::http::message::BasicHttpEntityEnclosingRequest,4,"setEntity","(Lorg/apache/http/HttpEntity;)V")
J2CPP_DEFINE_METHOD(org::apache::http::message::BasicHttpEntityEnclosingRequest,5,"expectContinue","()Z")

} //namespace j2cpp

#endif //J2CPP_ORG_APACHE_HTTP_MESSAGE_BASICHTTPENTITYENCLOSINGREQUEST_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
