/*================================================================================
  code generated by: java2cpp
  class: android.graphics.PorterDuffColorFilter
================================================================================*/


#ifndef J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_GRAPHICS_PORTERDUFFCOLORFILTER_HPP_DECL
#define J2CPP_ANDROID_GRAPHICS_PORTERDUFFCOLORFILTER_HPP_DECL


namespace j2cpp { namespace android { namespace graphics { namespace PorterDuff_ { class Mode; } } } }


#include <android/graphics/PorterDuff.hpp>


namespace j2cpp {

namespace android { namespace graphics {

	class PorterDuffColorFilter;
	class PorterDuffColorFilter
		: public cpp_object<PorterDuffColorFilter>
	{
	public:

		J2CPP_DECLARE_CLASS

		J2CPP_DECLARE_METHOD(0)

		PorterDuffColorFilter(jobject jobj)
		: cpp_object<PorterDuffColorFilter>(jobj)
		{
		}

	}; //class PorterDuffColorFilter

} //namespace graphics
} //namespace android


} //namespace j2cpp

#endif //J2CPP_ANDROID_GRAPHICS_PORTERDUFFCOLORFILTER_HPP_DECL

#else //J2CPP_INCLUDE_IMPLEMENTATION

#ifndef J2CPP_ANDROID_GRAPHICS_PORTERDUFFCOLORFILTER_HPP_IMPL
#define J2CPP_ANDROID_GRAPHICS_PORTERDUFFCOLORFILTER_HPP_IMPL

namespace j2cpp {


template <>
local_ref< android::graphics::PorterDuffColorFilter > create< android::graphics::PorterDuffColorFilter>(cpp_int const &a0, local_ref< android::graphics::PorterDuff_::Mode > const &a1)
{
	return local_ref< android::graphics::PorterDuffColorFilter >(
		environment::get().get_jenv()->NewObject(
			get_class<android::graphics::PorterDuffColorFilter::J2CPP_CLASS_NAME>(),
			get_method_id<android::graphics::PorterDuffColorFilter::J2CPP_CLASS_NAME, android::graphics::PorterDuffColorFilter::J2CPP_METHOD_NAME(0), android::graphics::PorterDuffColorFilter::J2CPP_METHOD_SIGNATURE(0), false>(),
			a0.get_jtype(), a1.get_jtype()
		)
	);
}


J2CPP_DEFINE_CLASS(android::graphics::PorterDuffColorFilter,"android/graphics/PorterDuffColorFilter")
J2CPP_DEFINE_METHOD(android::graphics::PorterDuffColorFilter,0,"<init>","(ILandroid/graphics/PorterDuff$Mode;)V")

} //namespace j2cpp

#endif //J2CPP_ANDROID_GRAPHICS_PORTERDUFFCOLORFILTER_HPP_IMPL

#endif //J2CPP_INCLUDE_IMPLEMENTATION
